import { TableColumnDefinition } from 'src/app/shared/truckassist-table/models/truckassist-table';

// APPLICANT TABLE COLUMNS DEFINITION
export function getApplicantColumnsDefinition() {
  return [
    {
      ngTemplate: 'checkboxTemplate',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'linkFieldTemplate',
      title: 'Name',
      field: 'name',
      name: 'Name',
      hidden: false,
      width: 170,
      pdfWidth: 10,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: true,
      linkField: {
        routerLinkStart: '',
        routerLinkEnd: '',
      },
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Dob',
      field: 'dob',
      name: 'Dob',
      hidden: false,
      width: 119,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Phone',
      field: 'phone',
      name: 'Phone',
      hidden: false,
      width: 108,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Email',
      field: 'email',
      name: 'Email',
      hidden: false,
      width: 153,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'superCheckboxTemplate',
      title: 'App.',
      field: 'app',
      name: 'App.',
      hidden: false,
      width: 55,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'superCheckboxTemplate',
      title: 'MVR',
      field: 'mvr',
      name: 'MVR',
      hidden: false,
      width: 55,
      filter: '',
      isNumeric: true,
      isDate: true,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'superCheckboxTemplate',
      title: 'PSP',
      field: 'psp',
      name: 'PSP',
      isComputed: false,
      hidden: false,
      width: 55,
      filter: '',
      isNumeric: true,
      isDate: true,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'superCheckboxTemplate',
      title: 'SPH',
      field: 'sph',
      name: 'SPH',
      hidden: false,
      width: 55,
      filter: '',
      isNumeric: true,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'superCheckboxTemplate',
      title: 'SSN',
      field: 'ssn',
      name: 'SSN',
      hidden: false,
      width: 55,
      filter: '',
      isNumeric: true,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'progressTemplate',
      title: 'Medical',
      field: 'medical[0].endDate',
      name: 'Medical',
      hidden: false,
      width: 145,
      filter: '',
      isNumeric: true,
      index: 10,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: {
        start: 'cdl[0].startDate',
        end: 'cdl[0].endDate',
      },
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'progressTemplate',
      title: 'CDL',
      field: 'cdl[0].endDate',
      name: 'CDL',
      hidden: false,
      width: 139,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: {
        start: 'cdl[0].startDate',
        end: 'cdl[0].endDate',
      },
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'revTemplate',
      title: 'Rev',
      field: 'rev',
      name: 'Rev',
      hidden: false,
      width: 45,
      filter: '',
      isNumeric: false,
      index: 12,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'filesTemplate',
      title: '',
      field: 'files',
      name: 'Files',
      hidden: false,
      width: 50,
      filter: '',
      isNumeric: true,
      index: 13,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'noteTemplate',
      title: '',
      field: 'note',
      name: 'Note',
      hidden: false,
      width: 50,
      filter: '',
      isNumeric: true,
      index: 14,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'actionTemplate',
      title: '',
      field: 'action',
      name: 'Action',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 15,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
  ] as TableColumnDefinition[];
}
