import { TableColumnDefinition } from 'src/app/shared/truckassist-table/models/truckassist-table';

// ACCIDENTS COLUMN DEFINITION
export function getAccidentColumns() {
  return [
    {
      ngTemplate: 'checkboxTemplate',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Report #',
      field: 'report',
      name: 'Report #',
      hidden: false,
      width: 160,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'avatarTemplate',
      title: 'Driver',
      field: 'driverFullName',
      name: 'Driver',
      hidden: false,
      width: 212,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      avatar: {
        src: 'doc.additionalData.avatar.src',
        routerLinkStart: '/drivers/edit/',
        routerLinkEnd: '/basic',
      },
      export: true,
      resizable: true,
      class: 'overflow-unset',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Date',
      field: 'eventDate',
      name: 'Date',
      hidden: false,
      width: 69,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Time',
      field: 'time',
      name: 'Time',
      hidden: false,
      width: 79,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Truck',
      field: 'truckNumber',
      name: 'Truck',
      hidden: false,
      width: 74,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Trailer',
      field: 'trailerNumber',
      name: 'Trailer',
      hidden: false,
      width: 94,
      filter: '',
      isNumeric: false,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Location',
      field: 'address',
      name: 'Location',
      hidden: false,
      width: 252,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },

    {
      ngTemplate: 'defaultTemplate',
      title: 'Fat.',
      field: 'fatality',
      name: 'Fat.',
      hidden: false,
      width: 59,
      filter: '',
      isNumeric: false,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Inj.',
      field: 'injuries',
      name: 'Inj.',
      hidden: false,
      width: 51,
      filter: '',
      isNumeric: false,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Tow',
      field: 'towing',
      name: 'Tow',
      hidden: false,
      width: 58,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'HM',
      field: 'hm',
      name: 'HM',
      hidden: false,
      width: 53,
      filter: '',
      isNumeric: false,
      index: 10,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'INS. Claim #',
      field: 'insuranceClaim',
      name: 'INS. Claim #',
      hidden: false,
      width: 127,
      filter: '',
      isNumeric: false,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'filesTemplate',
      title: '',
      field: 'files',
      name: 'Files',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 12,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'noteTemplate',
      title: '',
      field: 'note',
      name: 'Note',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 13,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'actionTemplate',
      title: '',
      field: 'action',
      name: 'Action',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 14,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: true,
      export: false,
      resizable: false,
    },
  ] as TableColumnDefinition[];
}

// ACCIDENTS COLUMN DEFINITION
export function getExtendedAccidentColumns() {
  return [
    {
      ngTemplate: 'checkboxTemplate',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Report #',
      field: 'report',
      name: 'Report #',
      hidden: false,
      width: 160,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'avatarTemplate',
      title: 'Driver',
      field: 'driverFullName',
      name: 'Driver',
      hidden: false,
      width: 212,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      avatar: {
        src: 'doc.additionalData.avatar.src',
        routerLinkStart: '/drivers/edit/',
        routerLinkEnd: '/basic',
      },
      export: true,
      resizable: true,
      class: 'overflow-unset',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Date',
      field: 'eventDate',
      name: 'Date',
      hidden: false,
      width: 69,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Time',
      field: 'time',
      name: 'Time',
      hidden: false,
      width: 79,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Truck',
      field: 'truckNumber',
      name: 'Truck',
      hidden: false,
      width: 74,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Trailer',
      field: 'trailerNumber',
      name: 'Trailer',
      hidden: false,
      width: 94,
      filter: '',
      isNumeric: false,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Location',
      field: 'address',
      name: 'Location',
      hidden: false,
      width: 252,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },

    {
      ngTemplate: 'defaultTemplate',
      title: 'Fat.',
      field: 'fatality',
      name: 'Fat.',
      hidden: false,
      width: 59,
      filter: '',
      isNumeric: false,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Inj.',
      field: 'injuries',
      name: 'Inj.',
      hidden: false,
      width: 51,
      filter: '',
      isNumeric: false,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Tow',
      field: 'towing',
      name: 'Tow',
      hidden: false,
      width: 58,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'HM',
      field: 'hm',
      name: 'HM',
      hidden: false,
      width: 53,
      filter: '',
      isNumeric: false,
      index: 10,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'INS. Claim #',
      field: 'insuranceClaim',
      name: 'INS. Claim #',
      hidden: false,
      width: 127,
      filter: '',
      isNumeric: false,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'filesTemplate',
      title: '',
      field: 'files',
      name: 'Files',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 12,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'noteTemplate',
      title: '',
      field: 'note',
      name: 'Note',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 13,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'actionTemplate',
      title: '',
      field: 'action',
      name: 'Action',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 14,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: true,
      export: false,
      resizable: false,
    },
  ] as TableColumnDefinition[];
}

/* VIOLATION COLUMN DEFINITION */
export function getViolationsColums() {
  return [
    {
      ngTemplate: 'checkboxTemplate',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'linkFieldTemplate',
      title: 'Report #',
      field: 'report',
      name: 'Report #',
      hidden: false,
      width: 147,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: {
        routerLinkStart: '/safety/violation/edit/',
        routerLinkEnd: '/details',
      },
    },
    {
      ngTemplate: 'avatarTemplate',
      title: 'Driver',
      field: 'driverFullName',
      name: 'Driver',
      hidden: false,
      width: 158,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      avatar: {
        src: 'doc.additionalData.avatar.src',
        routerLinkStart: '/drivers/edit/',
        routerLinkEnd: '/basic',
      },
      export: true,
      resizable: true,
      class: 'overflow-unset',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Date',
      field: 'eventDate',
      name: 'Date',
      hidden: false,
      width: 75,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Time',
      field: 'hm',
      name: 'Time',
      hidden: false,
      width: 76,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Truck',
      field: 'truckNumber',
      name: 'Truck',
      hidden: false,
      width: 77,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Trailer',
      field: 'trailerNumber',
      name: 'Trailer',
      hidden: false,
      width: 78,
      filter: '',
      isNumeric: false,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'oosTemplate',
      title: 'OOS',
      field: 'oos',
      name: 'OOS',
      hidden: false,
      width: 111,
      filter: '',
      isNumeric: false,
      index: 7,
      sortable: false,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      outOfService: true,
    },
    {
      ngTemplate: 'stateTemplate',
      title: 'State',
      field: 'state',
      name: 'State',
      hidden: false,
      width: 71,
      filter: '',
      isNumeric: false,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: {
        urlStart: '../assets/img/svgs/states/',
        field: 'state',
        urlEnd: '.svg',
      },
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'LVL',
      field: 'lvl',
      name: 'LVL',
      hidden: false,
      width: 55,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'violationTemplate',
      title: '',
      field: 'vl1',
      name: 'vl1',
      hidden: false,
      width: 50,
      filter: '',
      isNumeric: false,
      index: 10,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: 'violationTemplate',
      title: '',
      field: 'vl2',
      name: 'vl2',
      hidden: false,
      width: 50,
      filter: '',
      isNumeric: false,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: 'violationTemplate',
      title: '',
      field: 'vl3',
      name: 'vl3',
      hidden: false,
      width: 50,
      filter: '',
      isNumeric: false,
      index: 12,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: 'violationTemplate',
      title: '',
      field: 'vl4',
      name: 'vl4',
      hidden: false,
      width: 50,
      filter: '',
      isNumeric: false,
      index: 13,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: 'violationTemplate',
      title: '',
      field: 'vl5',
      name: 'vl5',
      hidden: false,
      width: 50,
      filter: '',
      isNumeric: false,
      index: 14,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: 'violationTemplate',
      title: '',
      field: 'vl6',
      name: 'vl6',
      hidden: false,
      width: 50,
      filter: '',
      isNumeric: false,
      index: 15,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: 'violationTemplate',
      title: '',
      field: 'vl7',
      name: 'vl7',
      hidden: false,
      width: 50,
      filter: '',
      isNumeric: false,
      index: 16,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: 'citationTemplate',
      title: 'Citation',
      field: 'citation',
      name: 'Citation',
      hidden: false,
      width: 90,
      filter: '',
      isNumeric: false,
      index: 17,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      citation: true,
    },
    {
      ngTemplate: 'filesTemplate',
      title: '',
      field: 'files',
      name: 'Files',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 18,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'noteTemplate',
      title: '',
      field: 'note',
      name: 'Note',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 19,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'actionTemplate',
      title: '',
      field: 'action',
      name: 'Action',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 20,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: true,
      export: false,
      resizable: false,
    },
  ] as TableColumnDefinition[];
}

/* VIOLATION EXTENDED COLUMN DEFINITION */
export function getExtendedViolationsColums() {
  return [
    {
      ngTemplate: 'checkboxTemplate',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'linkFieldTemplate',
      title: 'Report #',
      field: 'report',
      name: 'Report #',
      hidden: false,
      width: 147,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: {
        routerLinkStart: '/safety/violation/edit/',
        routerLinkEnd: '/details',
      },
    },
    {
      ngTemplate: 'avatarTemplate',
      title: 'Driver',
      field: 'driverFullName',
      name: 'Driver',
      hidden: false,
      width: 158,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      avatar: {
        src: 'doc.additionalData.avatar.src',
        routerLinkStart: '/drivers/edit/',
        routerLinkEnd: '/basic',
      },
      export: true,
      resizable: true,
      class: 'overflow-unset',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Date',
      field: 'eventDate',
      name: 'Date',
      hidden: false,
      width: 75,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Time',
      field: 'hm',
      name: 'Time',
      hidden: false,
      width: 76,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Truck',
      field: 'truckNumber',
      name: 'Truck',
      hidden: false,
      width: 77,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Trailer',
      field: 'trailerNumber',
      name: 'Trailer',
      hidden: false,
      width: 78,
      filter: '',
      isNumeric: false,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'oosTemplate',
      title: 'OOS',
      field: 'oos',
      name: 'OOS',
      hidden: false,
      width: 111,
      filter: '',
      isNumeric: false,
      index: 7,
      sortable: false,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      outOfService: true,
    },
    {
      ngTemplate: 'stateTemplate',
      title: 'State',
      field: 'state',
      name: 'State',
      hidden: false,
      width: 71,
      filter: '',
      isNumeric: false,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: {
        urlStart: '../assets/img/svgs/states/',
        field: 'state',
        urlEnd: '.svg',
      },
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'LVL',
      field: 'lvl',
      name: 'LVL',
      hidden: false,
      width: 55,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'violationTemplate',
      title: '',
      field: 'vl1',
      name: 'vl1',
      hidden: false,
      width: 50,
      filter: '',
      isNumeric: false,
      index: 10,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: 'violationTemplate',
      title: '',
      field: 'vl2',
      name: 'vl2',
      hidden: false,
      width: 50,
      filter: '',
      isNumeric: false,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: 'violationTemplate',
      title: '',
      field: 'vl3',
      name: 'vl3',
      hidden: false,
      width: 50,
      filter: '',
      isNumeric: false,
      index: 12,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: 'violationTemplate',
      title: '',
      field: 'vl4',
      name: 'vl4',
      hidden: false,
      width: 50,
      filter: '',
      isNumeric: false,
      index: 13,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: 'violationTemplate',
      title: '',
      field: 'vl5',
      name: 'vl5',
      hidden: false,
      width: 50,
      filter: '',
      isNumeric: false,
      index: 14,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: 'violationTemplate',
      title: '',
      field: 'vl6',
      name: 'vl6',
      hidden: false,
      width: 50,
      filter: '',
      isNumeric: false,
      index: 15,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: 'violationTemplate',
      title: '',
      field: 'vl7',
      name: 'vl7',
      hidden: false,
      width: 50,
      filter: '',
      isNumeric: false,
      index: 16,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      violation: true,
    },
    {
      ngTemplate: 'citationTemplate',
      title: 'Citation',
      field: 'citation',
      name: 'Citation',
      hidden: false,
      width: 90,
      filter: '',
      isNumeric: false,
      index: 17,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      citation: true,
    },
    {
      ngTemplate: 'filesTemplate',
      title: '',
      field: 'files',
      name: 'Files',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 18,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'noteTemplate',
      title: '',
      field: 'note',
      name: 'Note',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 19,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'actionTemplate',
      title: '',
      field: 'action',
      name: 'Action',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 20,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: true,
      export: false,
      resizable: false,
    },
  ] as TableColumnDefinition[];
}
/* VIOLATION SUMMARY COLUMN DEFINITION */
export function getViolationsSummaryColums() {
  return [
    {
      ngTemplate: 'defaultTemplate',
      title: '#',
      field: 'violationNumber',
      name: 'violationNumber',
      hidden: false,
      width: 36,
      filter: '',
      isNumeric: true,
      index: 0,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Code',
      field: 'code',
      name: 'Code',
      hidden: false,
      width: 155,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Description',
      field: 'codeDescription',
      name: 'Description',
      hidden: false,
      width: 1128,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'OOS',
      field: 'oosNumber',
      name: 'OOS',
      hidden: false,
      width: 69,
      filter: '',
      isNumeric: true,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'SW',
      field: 'severityWeight',
      name: 'SW',
      hidden: false,
      width: 52,
      filter: '',
      isNumeric: true,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
  ] as TableColumnDefinition[];
}

/* VIOLATION SUMMARY EXTENDED COLUMN DEFINITION */
export function getExtendedViolationsSummaryColums() {
  return [
    {
      ngTemplate: 'defaultTemplate',
      title: '#',
      field: 'violationNumber',
      name: 'violationNumber',
      hidden: false,
      width: 36,
      filter: '',
      isNumeric: true,
      index: 0,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Code',
      field: 'code',
      name: 'Code',
      hidden: false,
      width: 155,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Description',
      field: 'codeDescription',
      name: 'Description',
      hidden: false,
      width: 1128,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'OOS',
      field: 'oosNumber',
      name: 'OOS',
      hidden: false,
      width: 69,
      filter: '',
      isNumeric: true,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'SW',
      field: 'severityWeight',
      name: 'SW',
      hidden: false,
      width: 52,
      filter: '',
      isNumeric: true,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
  ] as TableColumnDefinition[];
}
