import { TableColumnDefinition } from 'src/app/shared/truckassist-table/models/truckassist-table';

export function getToolsAccountsColumnDefinition() {
  return [
    {
      ngTemplate: 'checkboxTemplate',
      title: '',
      field: 'select',
      name: 'Select',
      isComputed: true,
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Name',
      field: 'name',
      name: 'Name',
      isComputed: false,
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Url',
      field: 'url',
      name: 'Url',
      isComputed: false,
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      navigateTo: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Username',
      field: 'username',
      name: 'Username',
      isComputed: false,
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
      imageHover: null,
    },
    {
      ngTemplate: 'passwordTemplate',
      title: 'Password',
      field: '',
      name: 'Password',
      isComputed: false,
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      password: true,
    },
    {
      ngTemplate: 'labelTemplate',
      title: 'Label',
      field: 'labelId',
      name: 'Label',
      isComputed: false,
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: false,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      imageHover: null,
      showLabel: true,
    },
    {
      ngTemplate: 'noteTemplate',
      title: '',
      field: 'doc.note',
      name: 'Note',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 7,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'actionTemplate',
      title: '',
      field: 'action',
      name: 'Action',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: true,
      index: 8,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: true,
    },
  ] as TableColumnDefinition[];
}


export function getExtendedToolsAccountsColumnDefinition() {
  return [
    {
      ngTemplate: 'checkboxTemplate',
      title: '',
      field: 'select',
      name: 'Select',
      isComputed: true,
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Name',
      field: 'name',
      name: 'Name',
      isComputed: false,
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Url',
      field: 'url',
      name: 'Url',
      isComputed: false,
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      navigateTo: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Username',
      field: 'username',
      name: 'Username',
      isComputed: false,
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
      imageHover: null,
    },
    {
      ngTemplate: 'passwordTemplate',
      title: 'Password',
      field: '',
      name: 'Password',
      isComputed: false,
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      password: true,
    },
    {
      ngTemplate: 'labelTemplate',
      title: 'Label',
      field: 'labelId',
      name: 'Label',
      isComputed: false,
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: false,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      imageHover: null,
      showLabel: true,
    },
    {
      ngTemplate: 'noteTemplate',
      title: '',
      field: 'doc.note',
      name: 'Note',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 7,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'actionTemplate',
      title: '',
      field: 'action',
      name: 'Action',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: true,
      index: 8,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: true,
    },
  ] as TableColumnDefinition[];
}
