import { TableColumnDefinition } from 'src/app/shared/truckassist-table/models/truckassist-table';

export function getTrailerColumnDefinition() {
  return [
    {
      ngTemplate: 'checkboxTemplate',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 32,
      pdfWidth: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: false,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'linkFieldTemplate',
      title: 'Unit#',
      field: 'trailerNumber',
      name: 'Unit#',
      hidden: false,
      width: 104,
      pdfWidth: 10,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: true,
      linkField: {
        routerLinkStart: '/trailers/edit/',
        routerLinkEnd: '/detail',
      },
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Year',
      field: 'doc.additionalData.year',
      name: 'Year',
      hidden: false,
      width: 69,
      pdfWidth: 10,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'svgTemplate',
      title: 'Make',
      field: 'doc.additionalData.make.name',
      name: 'Make',
      hidden: false,
      width: 130,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      imageHover: {
        url: '../assets/img/svgs/trailer/makers/',
        file: 'doc.additionalData.make.file',
      },
      class: 'make-icon',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Model',
      field: 'doc.additionalData.model',
      name: 'Model',
      hidden: false,
      width: 116,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'colorTemplate',
      title: 'Color',
      field: 'doc.additionalData.color.key',
      name: 'Color',
      hidden: false,
      width: 83,
      pdfWidth: 10,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      colorTemplate: {
        value: 'doc.additionalData.color.value',
      },
      opacityIgnore: true,
      class: 'overflow-unset'
    },
    {
      ngTemplate: 'svgTemplate',
      title: 'Type',
      field: 'doc.additionalData.type.name',
      name: 'Type',
      hidden: false,
      width: 97,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: false,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      imageHover: {
        url: '../assets/img/svgs/trailer/',
        file: 'doc.additionalData.type.file',
        class: 'doc.additionalData.type.class',
      },
      class: 'type-icon',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'VIN',
      field: 'vin',
      name: 'VIN',
      hidden: false,
      width: 200,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Lic. Plate',
      field: 'doc.licenseData[0].licensePlate',
      name: 'Lic. Plate',
      hidden: false,
      width: 130,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
      class: 'custom-font',
    },
    {
      ngTemplate: 'progressTemplate',
      title: 'Annual insp.',
      field: 'doc.inspectionData[0].startDate',
      name: 'Annual insp.',
      hidden: false,
      width: 166,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: {
        start: '',
        end: 'doc.inspectionData[0].startDate',
      },
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Owner',
      field: 'ownerName',
      name: 'Owner',
      hidden: false,
      width: 140,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 10,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Length',
      field: 'doc.additionalData.length.value',
      name: 'Length',
      hidden: false,
      width: 85,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'noteTemplate',
      title: '',
      field: 'doc.additionalData.note',
      name: 'Note',
      hidden: false,
      width: 40,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 12,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'actionTemplate',
      title: '',
      field: 'action',
      name: 'Action',
      hidden: false,
      width: 40,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 13,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
  ] as TableColumnDefinition[];
}

export function getExtendedTrailerColumnDefinition() {
  return [
    {
      ngTemplate: 'checkboxTemplate',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 40,
      pdfWidth: 40,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: false,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'linkFieldTemplate',
      title: 'Unit#',
      field: 'trailerNumber',
      name: 'Unit#',
      hidden: false,
      width: 104,
      pdfWidth: 10,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: true,
      linkField: {
        routerLinkStart: '/trailers/edit/',
        routerLinkEnd: '/detail',
      },
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Year',
      field: 'doc.additionalData.year',
      name: 'Year',
      hidden: false,
      width: 69,
      pdfWidth: 10,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'svgTemplate',
      title: 'Make',
      field: 'doc.additionalData.make.name',
      name: 'Make',
      hidden: false,
      width: 130,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      imageHover: {
        url: '../assets/img/svgs/trailer/makers/',
        file: 'doc.additionalData.make.file',
      },
      class: 'make-icon',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Model',
      field: 'doc.additionalData.model',
      name: 'Model',
      hidden: false,
      width: 116,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'colorTemplate',
      title: 'Color',
      field: 'doc.additionalData.color.key',
      name: 'Color',
      hidden: false,
      width: 83,
      pdfWidth: 10,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      colorTemplate: {
        value: 'doc.additionalData.color.value',
      },
      opacityIgnore: true,
    },
    {
      ngTemplate: 'svgTemplate',
      title: 'Type',
      field: 'doc.additionalData.type.name',
      name: 'Type',
      hidden: false,
      width: 97,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: false,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      imageHover: {
        url: '../assets/img/svgs/trailer/',
        file: 'doc.additionalData.type.file',
        class: 'doc.additionalData.type.class',
      },
      class: 'type-icon',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'VIN',
      field: 'vin',
      name: 'VIN',
      hidden: false,
      width: 200,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Lic. Plate',
      field: 'doc.licenseData[0].licensePlate',
      name: 'Lic. Plate',
      hidden: false,
      width: 130,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
      class: 'custom-font',
    },
    {
      ngTemplate: 'progressTemplate',
      title: 'Annual insp.',
      field: 'doc.inspectionData[0].startDate',
      name: 'Annual insp.',
      hidden: false,
      width: 166,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: {
        start: '',
        end: 'doc.inspectionData[0].startDate',
      },
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Owner',
      field: 'ownerName',
      name: 'Owner',
      hidden: false,
      width: 140,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 10,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Length',
      field: 'doc.additionalData.length.value',
      name: 'Length',
      hidden: false,
      width: 85,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'noteTemplate',
      title: '',
      field: 'doc.additionalData.note',
      name: 'Note',
      hidden: false,
      width: 40,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 12,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'actionTemplate',
      title: '',
      field: 'action',
      name: 'Action',
      hidden: false,
      width: 40,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 13,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
  ] as TableColumnDefinition[];
}
