import { TableColumnDefinition } from 'src/app/shared/truckassist-table/models/truckassist-table';

export function getTruckColumnDefinition() {
  return [
    {
      ngTemplate: 'checkboxTemplate',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 32,
      pdfWidth: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: false,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'linkFieldTemplate',
      title: 'Unit#',
      field: 'truckNumber',
      name: 'Unit#',
      hidden: false,
      width: 66,
      pdfWidth: 10,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: true,
      linkField: {
        routerLinkStart: '/trucks/edit/',
        routerLinkEnd: '/detail',
      },
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Year',
      field: 'doc.additionalData.year',
      name: 'Year',
      hidden: false,
      width: 65,
      pdfWidth: 10,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'svgTemplate',
      title: 'Make',
      field: 'doc.additionalData.make.name',
      name: 'Make',
      hidden: false,
      width: 146,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      imageHover: {
        url: '../assets/img/svgs/truck/makers/',
        file: 'doc.additionalData.make.file',
      },
      class: 'make-icon',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Model',
      field: 'doc.additionalData.model',
      name: 'Model',
      hidden: false,
      width: 137,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'colorTemplate',
      title: 'Color',
      field: 'doc.additionalData.color.key',
      name: 'Color',
      hidden: false,
      width: 54,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      colorTemplate: {
        value: 'doc.additionalData.color.value',
      },
      opacityIgnore: true,
      class: 'overflow-unset'
    },
    {
      ngTemplate: 'svgTemplate',
      title: 'Type',
      field: 'doc.additionalData.type.name',
      name: 'Type',
      hidden: false,
      width: 83,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: false,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      imageHover: {
        url: '../assets/img/svgs/truck/',
        file: 'doc.additionalData.type.file',
        class: 'doc.additionalData.type.class',
      },
      class: 'type-icon',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'VIN',
      field: 'vin',
      name: 'VIN',
      hidden: false,
      width: 195,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Lic. Plate',
      field: 'doc.licenseData[0].licensePlate',
      name: 'Lic. Plate',
      hidden: false,
      width: 119,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
      class: 'custom-font',
    },
    {
      ngTemplate: 'progressTemplate',
      title: 'Annual insp.',
      field: 'doc.inspectionData[0].startDate',
      name: 'Annual insp.',
      hidden: false,
      width: 147,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: {
        start: '',
        end: 'doc.inspectionData[0].startDate',
      },
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Owner',
      field: 'ownerName',
      name: 'Owner',
      hidden: false,
      width: 240,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Insurance Policy',
      field: 'doc.additionalData.insurancePolicyNumber',
      name: 'Insurance Policy',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Axies',
      field: 'doc.additionalData.axises',
      name: 'Axies',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Empty Weight',
      field: 'doc.additionalData.emptyWeight',
      name: 'Empty Weight',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Engine Type',
      field: 'doc.additionalData.engine.value',
      name: 'Engine Type',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Tire Size',
      field: 'doc.additionalData.tireSize.value',
      name: 'Tire Size',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Mileage',
      field: 'doc.additionalData.mileage',
      name: 'Mileage',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'IPAS / EZPASS',
      field: 'doc.additionalData.ipasEzpass',
      name: 'IPAS / EZPASS',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: '%',
      field: 'commission',
      name: 'Commission',
      hidden: false,
      width: 57,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
      empty: ['companyOwned', 'divisionFlag'],
      isProgress: true
    },
    {
      ngTemplate: 'noteTemplate',
      title: '',
      field: 'doc.additionalData.note',
      name: 'Note',
      hidden: false,
      width: 40,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 17,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'actionTemplate',
      title: '',
      field: 'action',
      name: 'Action',
      hidden: false,
      width: 40,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 16,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
  ] as TableColumnDefinition[];
}

export function getExtendedTruckColumnDefinition() {
  return [
    {
      ngTemplate: 'checkboxTemplate',
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 40,
      pdfWidth: 40,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: false,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      ngTemplate: 'linkFieldTemplate',
      title: 'Unit#',
      field: 'truckNumber',
      name: 'Unit#',
      hidden: false,
      width: 66,
      pdfWidth: 10,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: true,
      linkField: {
        routerLinkStart: '/trucks/edit/',
        routerLinkEnd: '/detail',
      },
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Year',
      field: 'doc.additionalData.year',
      name: 'Year',
      hidden: false,
      width: 65,
      pdfWidth: 10,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'svgTemplate',
      title: 'Make',
      field: 'doc.additionalData.make.name',
      name: 'Make',
      hidden: false,
      width: 146,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      imageHover: {
        url: '../assets/img/svgs/truck/makers/',
        file: 'doc.additionalData.make.file',
      },
      class: 'make-icon',
    },
    {
      title: 'Model',
      field: 'doc.additionalData.model',
      name: 'Model',
      hidden: false,
      width: 137,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'colorTemplate',
      title: 'Color',
      field: 'doc.additionalData.color.key',
      name: 'Color',
      hidden: false,
      width: 54,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      colorTemplate: {
        value: 'doc.additionalData.color.value',
      },
      opacityIgnore: true,
    },
    {
      ngTemplate: 'svgTemplate',
      title: 'Type',
      field: 'doc.additionalData.type.name',
      name: 'Type',
      hidden: false,
      width: 83,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: false,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      imageHover: {
        url: '../assets/img/svgs/truck/',
        file: 'doc.additionalData.type.file',
        class: 'doc.additionalData.type.class',
      },
      class: 'type-icon',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'VIN',
      field: 'vin',
      name: 'VIN',
      hidden: false,
      width: 195,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Lic. Plate',
      field: 'doc.licenseData[0].licensePlate',
      name: 'Lic. Plate',
      hidden: false,
      width: 119,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
      class: 'custom-font',
    },
    {
      ngTemplate: 'progressTemplate',
      title: 'Annual insp.',
      field: 'doc.inspectionData[0].startDate',
      name: 'Annual insp.',
      hidden: false,
      width: 147,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: {
        start: '',
        end: 'doc.inspectionData[0].startDate',
      },
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Owner',
      field: 'ownerName',
      name: 'Owner',
      hidden: false,
      width: 240,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Insurance Policy',
      field: 'doc.additionalData.insurancePolicyNumber',
      name: 'Insurance Policy',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Axies',
      field: 'doc.additionalData.axises',
      name: 'Axies',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Empty Weight',
      field: 'doc.additionalData.emptyWeight',
      name: 'Empty Weight',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Engine Type',
      field: 'doc.additionalData.engine.value',
      name: 'Engine Type',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Tire Size',
      field: 'doc.additionalData.tireSize.value',
      name: 'Tire Size',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Mileage',
      field: 'doc.additionalData.mileage',
      name: 'Mileage',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'IPAS / EZPASS',
      field: 'doc.additionalData.ipasEzpass',
      name: 'IPAS / EZPASS',
      hidden: true,
      width: 0,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: '%',
      field: 'commission',
      name: 'Commission',
      hidden: false,
      width: 57,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 11,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      linkField: null,
      empty: ['companyOwned', 'divisionFlag'],
      isProgress: true
    },
    {
      ngTemplate: 'noteTemplate',
      title: '',
      field: 'doc.additionalData.note',
      name: 'Note',
      hidden: false,
      width: 40,
      pdfWidth: 15,
      filter: '',
      isNumeric: false,
      index: 17,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: false,
    },
    {
      ngTemplate: 'actionTemplate',
      title: '',
      field: 'action',
      name: 'Action',
      hidden: false,
      width: 40,
      pdfWidth: 15,
      filter: '',
      isNumeric: true,
      index: 16,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
  ] as TableColumnDefinition[];
}
