import { TableColumnDefinition } from 'src/app/shared/truckassist-table/models/truckassist-table';

export function getUsersColumnDefinition() {
  return [
    {
      ngTemplate: 'userCheckboxTemplate',
      title: '',
      field: 'active',
      name: '',
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
      showUserCheckbox: true,
    },
    {
      ngTemplate: 'avatarTemplate',
      title: 'Name',
      field: 'userFullName',
      name: 'Name',
      hidden: false,
      width: 260,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      avatar: {
        src: 'doc.avatar.src',
      },
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'overflow-unset'
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Reg. Date',
      field: 'dateValue',
      name: 'Reg. Date',
      hidden: false,
      width: 150,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Phone',
      field: 'doc.phone',
      name: 'Phone',
      hidden: false,
      width: 190,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Email',
      field: 'email',
      name: 'Email',
      hidden: false,
      width: 350,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Type',
      field: 'userType',
      name: 'Type',
      hidden: false,
      width: 200,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      addFontToTableText: true,
    },
    {
      ngTemplate: 'deleteActionTemplate',
      title: '',
      field: 'delete-action',
      name: 'Action',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: true,
      index: 6,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: true,
    },
  ] as TableColumnDefinition[];
}


export function getExtendedUsersColumnDefinition() {
  return [
    {
      ngTemplate: 'userCheckboxTemplate',
      title: '',
      field: '',
      name: '',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
      showUserCheckbox: true,
    },
    {
      ngTemplate: 'avatarTemplate',
      title: 'Name',
      field: 'firstName',
      name: 'Name',
      hidden: false,
      width: 260,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      avatar: {
        src: 'doc.avatar.src',
      },
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Reg. Date',
      field: 'createdAt',
      name: 'Reg. Date',
      hidden: false,
      width: 150,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Phone',
      field: 'doc.phone',
      name: 'Phone',
      hidden: false,
      width: 190,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Email',
      field: 'email',
      name: 'Email',
      hidden: false,
      width: 350,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      ngTemplate: 'defaultTemplate',
      title: 'Type',
      field: 'userType',
      name: 'Type',
      hidden: false,
      width: 200,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      addFontToTableText: true,
    },
    {
      ngTemplate: 'deleteActionTemplate',
      title: '',
      field: 'delete-action',
      name: 'Action',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: true,
      index: 6,
      sortable: true,
      isActionColumn: true,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: true,
    },
  ] as TableColumnDefinition[];
}
