import { TableColumnDefinition } from 'src/app/shared/truckassist-table/models/truckassist-table';

export function getTruckTrailerIftaColumnDefinition() {
  return [
    {
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 32,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      title: 'Fuel',
      field: 'createdAt',
      name: 'Fuel',
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      title: 'Field',
      field: 'invoiceNo',
      name: 'Field',
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: 'Field',
      field: 'doc.total',
      name: 'Field',
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: 'Field',
      field: 'doc.millage',
      name: 'Field',
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: 'Field',
      field: 'doc.millage',
      name: 'Field',
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: '',
      field: 'action',
      name: 'Action',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 6,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
  ] as TableColumnDefinition[];
}

export function getExtendedTruckTrailerIftaColumnDefinition() {
  return [
    {
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      title: 'Fuel',
      field: 'createdAt',
      name: 'Fuel',
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      title: 'Field',
      field: 'invoiceNo',
      name: 'Field',
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: false,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: 'Field',
      field: 'doc.total',
      name: 'Field',
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: 'Field',
      field: 'doc.millage',
      name: 'Field',
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: 'Field',
      field: 'doc.millage',
      name: 'Field',
      hidden: false,
      width: 0,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: '',
      field: 'action',
      name: 'Action',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 6,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
  ] as TableColumnDefinition[];
}
