import { TableColumnDefinition } from 'src/app/shared/truckassist-table/models/truckassist-table';

// LOAD COLUMN DEFINITION
export function getTruckTrailerLoadColumnDefinition() {
  return [
    {
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      title: 'Inv.',
      field: 'loadNumber',
      name: 'Name',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: 'Broker',
      field: 'customerName',
      name: 'Broker',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: 'Ref #',
      field: 'customerLoadNumber',
      name: 'Ref #',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: 'Pick Date',
      field: 'pickupDateTime',
      name: 'Pick Date',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      title: 'Pick-Up',
      field: 'pickUp',
      name: 'Pick-Up',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      devFrom: true,
    },
    {
      title: 'Delivery',
      field: 'delivery',
      name: 'Delivery',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      devTo: true,
    },
    {
      title: 'Del. Date',
      field: 'deliveryDateTime',
      name: 'Del. Date',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      title: 'Total',
      field: 'total',
      name: 'Total',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: 'Status',
      field: 'status',
      name: 'Status',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      showStatus: true,
    },
    {
      title: 'Miles',
      field: 'mileage',
      name: 'Miles',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 10,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: '',
      field: 'doc.additionalData.note',
      name: 'Note',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 11,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: false,
    },
    {
      title: '',
      field: 'action',
      name: 'Action',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 12,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: true,
      export: false,
      resizable: false,
    },
  ] as TableColumnDefinition[];
}

// LOAD COLUMN DEFINITION
export function getExtendedTruckTrailerLoadColumnDefinition() {
  return [
    {
      title: '',
      field: 'select',
      name: 'Select',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 0,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: true,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: false,
      export: false,
      resizable: false,
    },
    {
      title: 'Inv.',
      field: 'loadNumber',
      name: 'Name',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 1,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: 'Broker',
      field: 'customerName',
      name: 'Broker',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: true,
      index: 2,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      avatar: null,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: 'Ref #',
      field: 'customerLoadNumber',
      name: 'Ref #',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 3,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: 'Pick Date',
      field: 'pickupDateTime',
      name: 'Pick Date',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 4,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      title: 'Pick-Up',
      field: 'pickUp',
      name: 'Pick-Up',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 5,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      devFrom: true,
    },
    {
      title: 'Delivery',
      field: 'delivery',
      name: 'Delivery',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 6,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      devTo: true,
    },
    {
      title: 'Del. Date',
      field: 'deliveryDateTime',
      name: 'Del. Date',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 7,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      class: 'custom-font',
    },
    {
      title: 'Total',
      field: 'total',
      name: 'Total',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 8,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: 'Status',
      field: 'status',
      name: 'Status',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 9,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
      showStatus: true,
    },
    {
      title: 'Miles',
      field: 'mileage',
      name: 'Miles',
      hidden: false,
      width: 133,
      filter: '',
      isNumeric: false,
      index: 10,
      sortable: true,
      isActionColumn: false,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: false,
      export: true,
      resizable: true,
    },
    {
      title: '',
      field: 'doc.additionalData.note',
      name: 'Note',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 11,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: true,
      disabled: true,
      export: true,
      resizable: false,
    },
    {
      title: '',
      field: 'action',
      name: 'Action',
      hidden: false,
      width: 40,
      filter: '',
      isNumeric: false,
      index: 12,
      sortable: false,
      isActionColumn: true,
      isSelectColumn: false,
      progress: null,
      hoverTemplate: null,
      filterable: false,
      disabled: true,
      export: false,
      resizable: false,
    },
  ] as TableColumnDefinition[];
}
