// export let driverTableColumns = [
//   {
//     name: 'Select',
//     resizable: false,
//     title: '',
//     hidden: false,
//     disabled: false,
//     field: 'select',
//     width: 45,
//     minWidth: 45,
//     maxWidth: 45,
//     orderIndex: 0,
//     sortable: false,
//     alignCenter: true,
//     number: false,
//     disableExport: true,
//     filterable: false,
//   },
//   {
//     name: 'Name',
//     resizable: true,
//     title: 'Name',
//     hidden: false,
//     disabled: true,
//     field: 'fullName',
//     width: 160,
//     minWidth: 50,
//     maxWidth: 180,
//     orderIndex: 1,
//     sortable: true,
//     alignCenter: false,
//     number: false,
//     disableExport: false,
//     filterable: true,
//   },
//   {
//     name: 'Phone',
//     resizable: true,
//     title: 'Phone',
//     hidden: false,
//     disabled: false,
//     field: 'mobile',
//     width: 120,
//     minWidth: 60,
//     maxWidth: 120,
//     orderIndex: 2,
//     sortable: true,
//     alignCenter: false,
//     number: false,
//     disableExport: false,
//     filterable: true,
//   },
//   {
//     name: 'Email',
//     resizable: true,
//     title: 'Email',
//     hidden: true,
//     disabled: false,
//     field: 'email',
//     width: 60,
//     minWidth: 30,
//     maxWidth: 80,
//     orderIndex: 3,
//     sortable: true,
//     alignCenter: false,
//     number: false,
//     disableExport: false,
//     filterable: true,
//   },
//   {
//     name: 'Address',
//     resizable: true,
//     title: 'Address',
//     hidden: true,
//     disabled: false,
//     field: 'street',
//     width: 60,
//     minWidth: 30,
//     maxWidth: 80,
//     orderIndex: 4,
//     sortable: true,
//     alignCenter: false,
//     number: false,
//     disableExport: false,
//     filterable: true,
//   },
//   {
//     name: 'SSN',
//     resizable: true,
//     title: 'SSN',
//     hidden: false,
//     disabled: false,
//     field: 'SSN',
//     width: 100,
//     minWidth: 50,
//     maxWidth: 120,
//     orderIndex: 5,
//     sortable: true,
//     alignCenter: false,
//     number: true,
//     disableExport: false,
//     filterable: true,
//   },
//   {
//     name: 'DOB',
//     resizable: true,
//     title: 'DOB',
//     hidden: false,
//     disabled: false,
//     field: 'licenses.birthdate',
//     width: 80,
//     minWidth: 40,
//     maxWidth: 100,
//     orderIndex: 6,
//     sortable: true,
//     alignCenter: false,
//     number: true,
//     disableExport: false,
//     filterable: true,
//   },
//   {
//     name: 'Hired',
//     resizable: true,
//     title: 'Hired',
//     hidden: false,
//     disabled: false,
//     field: 'workStartDate',
//     width: 80,
//     minWidth: 40,
//     maxWidth: 100,
//     orderIndex: 7,
//     sortable: true,
//     alignCenter: false,
//     number: true,
//     disableExport: false,
//     filterable: true,
//   },
//   {
//     name: 'CDL',
//     resizable: true,
//     title: 'CDL',
//     hidden: false,
//     disabled: false,
//     field: 'licenses.number',
//     width: 130,
//     minWidth: 40,
//     maxWidth: 150,
//     orderIndex: 8,
//     sortable: true,
//     alignCenter: false,
//     number: true,
//     disableExport: false,
//     filterable: true,
//   },
//   {
//     name: 'State',
//     resizable: true,
//     title: 'State',
//     hidden: false,
//     disabled: false,
//     field: 'licenses.stateName',
//     width: 60,
//     minWidth: 30,
//     maxWidth: 80,
//     orderIndex: 9,
//     sortable: true,
//     alignCenter: false,
//     number: false,
//     disableExport: false,
//     filterable: true,
//   },
//   {
//     name: 'Expiration',
//     resizable: true,
//     title: 'Expiration',
//     hidden: false,
//     disabled: false,
//     field: 'licenses.endDateTimeStamp',
//     width: 120,
//     minWidth: 60,
//     maxWidth: 130,
//     orderIndex: 10,
//     sortable: true,
//     alignCenter: false,
//     number: true,
//     disableExport: true,
//     filterable: false,
//   },
//   {
//     name: 'Medical',
//     resizable: true,
//     title: 'Medical',
//     hidden: false,
//     disabled: false,
//     field: 'medical.endDateTimeStamp',
//     width: 120,
//     minWidth: 60,
//     maxWidth: 130,
//     orderIndex: 11,
//     sortable: true,
//     alignCenter: false,
//     number: true,
//     disableExport: true,
//     filterable: false,
//   },
//   {
//     name: 'MVR',
//     resizable: true,
//     title: 'MVR',
//     hidden: false,
//     disabled: false,
//     field: 'mvrExpirationTimeStamp',
//     width: 120,
//     minWidth: 60,
//     maxWidth: 130,
//     orderIndex: 12,
//     sortable: true,
//     alignCenter: false,
//     number: true,
//     disableExport: true,
//     filterable: false,
//   },
//   {
//     name: 'Bank',
//     resizable: true,
//     title: 'Bank',
//     hidden: true,
//     disabled: false,
//     field: 'bankAccount.bankName',
//     width: 60,
//     minWidth: 30,
//     maxWidth: 80,
//     orderIndex: 13,
//     sortable: true,
//     alignCenter: false,
//     number: false,
//     disableExport: true,
//     filterable: true,
//   },
//   {
//     name: 'Account',
//     resizable: true,
//     title: 'Account',
//     hidden: true,
//     disabled: false,
//     field: 'bankAccount.accountNumber',
//     width: 60,
//     minWidth: 30,
//     maxWidth: 80,
//     orderIndex: 14,
//     sortable: true,
//     alignCenter: false,
//     number: true,
//     disableExport: false,
//     filterable: true,
//   },
//   {
//     name: 'Routing',
//     resizable: true,
//     title: 'Routing',
//     hidden: true,
//     disabled: false,
//     field: 'bankAccount.routingNumber',
//     width: 60,
//     minWidth: 30,
//     maxWidth: 80,
//     orderIndex: 15,
//     sortable: true,
//     alignCenter: false,
//     number: true,
//     disableExport: false,
//     filterable: true,
//   },
//   {
//     name: 'Files',
//     resizable: false,
//     title: '',
//     hidden: false,
//     disabled: false,
//     field: 'files',
//     width: 30,
//     minWidth: 30,
//     maxWidth: 30,
//     orderIndex: 16,
//     sortable: false,
//     alignCenter: true,
//     number: false,
//     disableExport: true,
//     filterable: false,
//   },
//   {
//     name: 'Note',
//     resizable: false,
//     title: '',
//     hidden: false,
//     disabled: false,
//     field: 'note',
//     width: 30,
//     minWidth: 30,
//     maxWidth: 30,
//     orderIndex: 17,
//     sortable: false,
//     alignCenter: true,
//     number: false,
//     disableExport: false,
//     filterable: true,
//   },
//   {
//     name: 'Action',
//     resizable: false,
//     title: '',
//     hidden: false,
//     disabled: false,
//     field: 'action',
//     width: 40,
//     minWidth: 40,
//     maxWidth: 40,
//     orderIndex: 18,
//     sortable: false,
//     alignCenter: true,
//     number: false,
//     disableExport: true,
//     filterable: false,
//   },
// ];
