import { SearchDataService } from 'src/app/core/services/search-data.service';
import { Component, OnInit, Input, ViewChild, EventEmitter, Output, OnDestroy } from '@angular/core';
import { animate, style, transition, trigger } from '@angular/animations';
import { AppCustomSearchComponent } from '../../shared/app-custom-search/app-custom-search.component';
import { ChipsFilter, SearchFilter, SearchFilterEvent } from 'src/app/core/model/shared/searchFilter';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';
@Component({
  selector: 'app-accounting-list',
  templateUrl: './accounting-list.component.html',
  styleUrls: ['./accounting-list.component.scss'],
  animations: [
    trigger('pickupAnimation', [
      transition(':enter', [style({ height: 100 }), animate('200ms', style({ height: '*' }))]),
      transition(':leave', [animate('200ms', style({ height: 0 }))]),
    ]),
  ],
})
export class AccountingListComponent implements OnInit, OnDestroy {
  private destroy$: Subject<void> = new Subject<void>();
  constructor(private searchDateService: SearchDataService) {}
  @Output() selectFromList = new EventEmitter();
  @ViewChild(AppCustomSearchComponent)
  customSearchComponent: AppCustomSearchComponent;
  listExpanded = false;
  showListCount = 1;
  showListNumber = 3;
  @Input() listTitle: string;
  @Input() userList: any;
  chipSearch: ChipsFilter;
  selectedUserIndex: number;

  public accountListTemp: any;

  accountList: any = [
    {
      id: 154,
      pickupLocation: {
        city: 'New York',
        state: 'New York',
        address: 'New York, NY, USA',
        country: 'US',
        zipCode: '',
        stateShortName: 'NY',
      },
      deliveryLocation: {
        city: 'Washington',
        state: 'District of Columbia',
        address: '14th St NW, Washington, DC, USA',
        country: 'US',
        zipCode: '',
        streetName: '14th Street Northwest',
        streetNumber: '',
        stateShortName: 'DC',
      },
      route: [
        {
          PointZip: '',
          distanceMiles: 0,
          PointCity: 'New York',
          PointType: 'start',
          ShipperId: 26,
          PointOrder: 1,
          PointState: 'NY',
          ShipperName: 'SHIPER123',
          PointAddress: 'New York, NY, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-22T22:00:00',
        },
        {
          PointZip: '',
          distanceMiles: 45,
          PointCity: 'Chicago',
          PointType: 'pickup',
          ShipperId: 27,
          PointOrder: 2,
          PointState: 'IL',
          ShipperName: 'SHIPP456',
          PointAddress: 'Chicago, IL, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-25T22:00:00',
        },
        {
          PointZip: '32034',
          distanceMiles: 475,
          PointCity: 'Fernandina Beach',
          PointType: 'delivery',
          ShipperId: 47,
          PointOrder: 1,
          PointState: 'FL',
          ShipperName: 'LONG ITEM',
          PointAddress: '94016 Woodbrier Cir, Fernandina Beach, FL 32034, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-26T22:00:00',
        },
        {
          PointZip: '',
          distanceMiles: 370,
          PointCity: 'Washington',
          PointType: 'delivery',
          ShipperId: 55,
          PointOrder: 2,
          PointState: 'DC',
          ShipperName: 'STREETSHIPPER',
          PointAddress: '14th St NW, Washington, DC, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-27T22:00:00',
        },
      ],
      companyId: 261,
      p_status: 'R',
      pay_value: '13200',
      pay_time: '01/10/2020 - 01/17/2020',
      driverUserId: 97,
      ssn: '545454545',
      password: null,
      firstName: 'Drive',
      lastName: 'Drivec',
      bankId: null,
      accountNumber: null,
      routingNumber: null,
      isOwner: 0,
      isOwnerAsCompany: 0,
      deviceId: null,
      status: 1,
      used: 1,
      protected: 0,
      createdAt: '2020-11-18T14:07:18',
      updatedAt: '2021-01-19T15:58:51',
      doc: {
        mvrData: [],
        testData: [],
        workData: [
          {
            id: 'c1876a04-1dee-4e06-abaf-8bd8d702c15a',
            endDate: null,
            startDate: '2020-11-18T14:07:18.282Z',
            endDateShort: null,
            startDateShort: '11/18/20',
          },
        ],
        licenseData: [],
        medicalData: [],
        additionalData: {
          note: 'dfafsa',
          type: 'single',
          email: 'driv@drive.com',
          phone: '(564) 656-5655',
          address: {
            city: 'Golden',
            state: 'Colorado',
            address: 'NREL Visitors Center, Golden, CO 80401, USA',
            country: 'US',
            zipCode: '80401',
            addressUnit: null,
            stateShortName: 'CO',
          },
          bankData: {
            id: null,
            bankLogo: null,
            bankName: null,
            bankLogoWide: null,
            accountNumber: null,
            routingNumber: null,
          },
          businessData: { taxId: null, isOwner: 0, businessName: null, isBusinessOwner: 0 },
          notifications: [],
        },
      },
    },
    {
      id: 155,
      pickupLocation: {
        city: 'New York',
        state: 'New York',
        address: 'New York, NY, USA',
        country: 'US',
        zipCode: '',
        stateShortName: 'NY',
      },
      deliveryLocation: {
        city: 'Washington',
        state: 'District of Columbia',
        address: '14th St NW, Washington, DC, USA',
        country: 'US',
        zipCode: '',
        streetName: '14th Street Northwest',
        streetNumber: '',
        stateShortName: 'DC',
      },
      route: [
        {
          PointZip: '',
          distanceMiles: 0,
          PointCity: 'New York',
          PointType: 'start',
          ShipperId: 26,
          PointOrder: 1,
          PointState: 'NY',
          ShipperName: 'SHIPER123',
          PointAddress: 'New York, NY, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-22T22:00:00',
        },
        {
          PointZip: '',
          distanceMiles: 45,
          PointCity: 'Chicago',
          PointType: 'pickup',
          ShipperId: 27,
          PointOrder: 2,
          PointState: 'IL',
          ShipperName: 'SHIPP456',
          PointAddress: 'Chicago, IL, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-25T22:00:00',
        },
        {
          PointZip: '32034',
          distanceMiles: 475,
          PointCity: 'Fernandina Beach',
          PointType: 'delivery',
          ShipperId: 47,
          PointOrder: 1,
          PointState: 'FL',
          ShipperName: 'LONG ITEM',
          PointAddress: '94016 Woodbrier Cir, Fernandina Beach, FL 32034, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-26T22:00:00',
        },
        {
          PointZip: '',
          distanceMiles: 370,
          PointCity: 'Washington',
          PointType: 'delivery',
          ShipperId: 55,
          PointOrder: 2,
          PointState: 'DC',
          ShipperName: 'STREETSHIPPER',
          PointAddress: '14th St NW, Washington, DC, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-27T22:00:00',
        },
      ],
      companyId: 261,
      p_status: 'R',
      pay_value: '13200',
      pay_time: '01/10/2020 - 01/17/2020',
      driverUserId: 98,
      ssn: '565656565',
      password: null,
      firstName: 'Drive',
      lastName: 'Drven',
      bankId: null,
      accountNumber: null,
      routingNumber: null,
      isOwner: 0,
      isOwnerAsCompany: 0,
      deviceId: null,
      status: 1,
      used: 1,
      protected: 0,
      createdAt: '2020-11-18T14:08:55',
      updatedAt: '2021-01-22T09:25:57',
      doc: {
        mvrData: [],
        testData: [],
        workData: [
          {
            id: 'babbd51c-38cd-4cc3-a79f-b788af6ad848',
            endDate: null,
            startDate: '2020-11-18T14:08:55.393Z',
            endDateShort: null,
            startDateShort: '11/18/20',
          },
        ],
        licenseData: [],
        medicalData: [],
        additionalData: {
          note: '',
          type: 'single',
          email: 'drv@drv.com',
          phone: '(555) 667-8999',
          address: {
            city: 'New York',
            state: 'New York',
            address: 'New York, NY, USA',
            country: 'US',
            zipCode: '',
            addressUnit: '2',
            stateShortName: 'NY',
          },
          bankData: {
            id: null,
            bankLogo: null,
            bankName: null,
            bankLogoWide: null,
            accountNumber: null,
            routingNumber: null,
          },
          businessData: { taxId: null, isOwner: 0, businessName: null, isBusinessOwner: 0 },
          notifications: [],
        },
      },
    },
    {
      id: 156,
      pickupLocation: {
        city: 'New York',
        state: 'New York',
        address: 'New York, NY, USA',
        country: 'US',
        zipCode: '',
        stateShortName: 'NY',
      },
      deliveryLocation: {
        city: 'Washington',
        state: 'District of Columbia',
        address: '14th St NW, Washington, DC, USA',
        country: 'US',
        zipCode: '',
        streetName: '14th Street Northwest',
        streetNumber: '',
        stateShortName: 'DC',
      },
      route: [
        {
          PointZip: '',
          distanceMiles: 0,
          PointCity: 'New York',
          PointType: 'start',
          ShipperId: 26,
          PointOrder: 1,
          PointState: 'NY',
          ShipperName: 'SHIPER123',
          PointAddress: 'New York, NY, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-22T22:00:00',
        },
        {
          PointZip: '',
          distanceMiles: 45,
          PointCity: 'Chicago',
          PointType: 'pickup',
          ShipperId: 27,
          PointOrder: 2,
          PointState: 'IL',
          ShipperName: 'SHIPP456',
          PointAddress: 'Chicago, IL, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-25T22:00:00',
        },
        {
          PointZip: '32034',
          distanceMiles: 475,
          PointCity: 'Fernandina Beach',
          PointType: 'delivery',
          ShipperId: 47,
          PointOrder: 1,
          PointState: 'FL',
          ShipperName: 'LONG ITEM',
          PointAddress: '94016 Woodbrier Cir, Fernandina Beach, FL 32034, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-26T22:00:00',
        },
        {
          PointZip: '',
          distanceMiles: 370,
          PointCity: 'Washington',
          PointType: 'delivery',
          ShipperId: 55,
          PointOrder: 2,
          PointState: 'DC',
          ShipperName: 'STREETSHIPPER',
          PointAddress: '14th St NW, Washington, DC, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-27T22:00:00',
        },
      ],
      companyId: 261,
      p_status: 'R',
      pay_value: '13200',
      pay_time: '01/10/2020 - 01/17/2020',
      driverUserId: 100,
      ssn: '656565656',
      password: null,
      firstName: 'Drivea',
      lastName: 'Drivernew',
      bankId: null,
      accountNumber: null,
      routingNumber: null,
      isOwner: 0,
      isOwnerAsCompany: 0,
      deviceId: null,
      status: 1,
      used: 1,
      protected: 0,
      createdAt: '2020-11-18T15:00:09',
      updatedAt: '2021-01-19T15:58:57',
      doc: {
        mvrData: [],
        testData: [],
        workData: [
          {
            id: '4284ae39-2916-4f9d-8672-2e1acdbfcbe4',
            endDate: null,
            startDate: '2020-11-18T15:00:09.275Z',
            endDateShort: null,
            startDateShort: '11/18/20',
          },
        ],
        licenseData: [],
        medicalData: [],
        additionalData: {
          note: 'dadas<div><br></div>',
          type: 'single',
          email: 'drv3@gmail.com',
          phone: '(555) 566-7788',
          address: {
            city: 'New Orleans',
            state: 'Louisiana',
            address: 'New Orleans, LA, USA',
            country: 'US',
            zipCode: '',
            addressUnit: null,
            stateShortName: 'LA',
          },
          bankData: {
            id: null,
            bankLogo: null,
            bankName: null,
            bankLogoWide: null,
            accountNumber: null,
            routingNumber: null,
          },
          businessData: { taxId: null, isOwner: 0, businessName: null, isBusinessOwner: 0 },
          notifications: [],
        },
      },
    },
    {
      id: 157,
      pickupLocation: {
        city: 'New York',
        state: 'New York',
        address: 'New York, NY, USA',
        country: 'US',
        zipCode: '',
        stateShortName: 'NY',
      },
      deliveryLocation: {
        city: 'Washington',
        state: 'District of Columbia',
        address: '14th St NW, Washington, DC, USA',
        country: 'US',
        zipCode: '',
        streetName: '14th Street Northwest',
        streetNumber: '',
        stateShortName: 'DC',
      },
      route: [
        {
          PointZip: '',
          distanceMiles: 0,
          PointCity: 'New York',
          PointType: 'start',
          ShipperId: 26,
          PointOrder: 1,
          PointState: 'NY',
          ShipperName: 'SHIPER123',
          PointAddress: 'New York, NY, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-22T22:00:00',
        },
        {
          PointZip: '',
          distanceMiles: 45,
          PointCity: 'Chicago',
          PointType: 'pickup',
          ShipperId: 27,
          PointOrder: 2,
          PointState: 'IL',
          ShipperName: 'SHIPP456',
          PointAddress: 'Chicago, IL, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-25T22:00:00',
        },
        {
          PointZip: '32034',
          distanceMiles: 475,
          PointCity: 'Fernandina Beach',
          PointType: 'delivery',
          ShipperId: 47,
          PointOrder: 1,
          PointState: 'FL',
          ShipperName: 'LONG ITEM',
          PointAddress: '94016 Woodbrier Cir, Fernandina Beach, FL 32034, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-26T22:00:00',
        },
        {
          PointZip: '',
          distanceMiles: 370,
          PointCity: 'Washington',
          PointType: 'delivery',
          ShipperId: 55,
          PointOrder: 2,
          PointState: 'DC',
          ShipperName: 'STREETSHIPPER',
          PointAddress: '14th St NW, Washington, DC, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-27T22:00:00',
        },
      ],
      companyId: 261,
      p_status: 'R',
      pay_value: '13200',
      pay_time: '01/10/2020 - 01/17/2020',
      driverUserId: 102,
      ssn: '343434343',
      password: null,
      firstName: 'Vozac',
      lastName: 'Man',
      bankId: null,
      accountNumber: null,
      routingNumber: null,
      isOwner: 0,
      isOwnerAsCompany: 0,
      deviceId: null,
      status: 1,
      used: 1,
      protected: 0,
      createdAt: '2020-11-19T10:43:20',
      updatedAt: '2021-01-19T11:05:12',
      doc: {
        mvrData: [],
        testData: [],
        workData: [
          {
            id: '3ef586cc-c238-44e9-886f-324d9f790744',
            endDate: null,
            startDate: '2020-11-19T10:43:20.157Z',
            endDateShort: null,
            startDateShort: '11/19/20',
          },
        ],
        licenseData: [],
        medicalData: [],
        additionalData: {
          note: null,
          type: 'single',
          email: 'voz@gmail.com',
          phone: '5550696966',
          address: {
            city: 'Chicago',
            state: 'Illinois',
            address: 'Chicago, IL, USA',
            country: 'US',
            zipCode: '',
            addressUnit: null,
            stateShortName: 'IL',
          },
          bankData: {
            id: null,
            bankLogo: null,
            bankName: null,
            bankLogoWide: null,
            accountNumber: null,
            routingNumber: null,
          },
          businessData: { taxId: null, isOwner: 0, businessName: null, isBusinessOwner: 0 },
          notifications: [],
        },
      },
    },
    {
      id: 181,
      pickupLocation: {
        city: 'New York',
        state: 'New York',
        address: 'New York, NY, USA',
        country: 'US',
        zipCode: '',
        stateShortName: 'NY',
      },
      deliveryLocation: {
        city: 'Washington',
        state: 'District of Columbia',
        address: '14th St NW, Washington, DC, USA',
        country: 'US',
        zipCode: '',
        streetName: '14th Street Northwest',
        streetNumber: '',
        stateShortName: 'DC',
      },
      route: [
        {
          PointZip: '',
          distanceMiles: 0,
          PointCity: 'New York',
          PointType: 'start',
          ShipperId: 26,
          PointOrder: 1,
          PointState: 'NY',
          ShipperName: 'SHIPER123',
          PointAddress: 'New York, NY, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-22T22:00:00',
        },
        {
          PointZip: '',
          distanceMiles: 45,
          PointCity: 'Chicago',
          PointType: 'pickup',
          ShipperId: 27,
          PointOrder: 2,
          PointState: 'IL',
          ShipperName: 'SHIPP456',
          PointAddress: 'Chicago, IL, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-25T22:00:00',
        },
        {
          PointZip: '32034',
          distanceMiles: 475,
          PointCity: 'Fernandina Beach',
          PointType: 'delivery',
          ShipperId: 47,
          PointOrder: 1,
          PointState: 'FL',
          ShipperName: 'LONG ITEM',
          PointAddress: '94016 Woodbrier Cir, Fernandina Beach, FL 32034, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-26T22:00:00',
        },
        {
          PointZip: '',
          distanceMiles: 370,
          PointCity: 'Washington',
          PointType: 'delivery',
          ShipperId: 55,
          PointOrder: 2,
          PointState: 'DC',
          ShipperName: 'STREETSHIPPER',
          PointAddress: '14th St NW, Washington, DC, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-27T22:00:00',
        },
      ],
      companyId: 261,
      p_status: 'R',
      pay_value: '13200',
      pay_time: '01/10/2020 - 01/17/2020',
      driverUserId: 155,
      ssn: '554447788',
      password: null,
      firstName: 'Vozac',
      lastName: 'Kam',
      bankId: null,
      accountNumber: null,
      routingNumber: null,
      isOwner: 0,
      isOwnerAsCompany: 0,
      deviceId: null,
      status: 1,
      used: 1,
      protected: 0,
      createdAt: '2020-12-04T09:38:14',
      updatedAt: '2021-01-19T12:29:16',
      doc: {
        mvrData: [],
        testData: [],
        workData: [
          {
            id: '8068709b-226d-4805-b793-e7e59d540e36',
            endDate: null,
            startDate: '2020-12-04T09:38:14.277Z',
            endDateShort: null,
            startDateShort: '12/4/20',
          },
        ],
        licenseData: [],
        medicalData: [],
        additionalData: {
          note: null,
          type: 'single',
          email: 'kam@kam.com',
          phone: '5556778899',
          address: {
            city: 'Los Angeles',
            state: 'California',
            address: 'Los Angeles, CA, USA',
            country: 'US',
            zipCode: '',
            addressUnit: '1',
            stateShortName: 'CA',
          },
          bankData: {
            id: null,
            bankLogo: null,
            bankName: null,
            bankLogoWide: null,
            accountNumber: null,
            routingNumber: null,
          },
          businessData: { taxId: null, isOwner: 0, businessName: null, isBusinessOwner: 0 },
          notifications: [],
        },
      },
    },
    {
      id: 186,
      pickupLocation: {
        city: 'New York',
        state: 'New York',
        address: 'New York, NY, USA',
        country: 'US',
        zipCode: '',
        stateShortName: 'NY',
      },
      deliveryLocation: {
        city: 'Washington',
        state: 'District of Columbia',
        address: '14th St NW, Washington, DC, USA',
        country: 'US',
        zipCode: '',
        streetName: '14th Street Northwest',
        streetNumber: '',
        stateShortName: 'DC',
      },
      route: [
        {
          PointZip: '',
          distanceMiles: 0,
          PointCity: 'New York',
          PointType: 'start',
          ShipperId: 26,
          PointOrder: 1,
          PointState: 'NY',
          ShipperName: 'SHIPER123',
          PointAddress: 'New York, NY, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-22T22:00:00',
        },
        {
          PointZip: '',
          distanceMiles: 45,
          PointCity: 'Chicago',
          PointType: 'pickup',
          ShipperId: 27,
          PointOrder: 2,
          PointState: 'IL',
          ShipperName: 'SHIPP456',
          PointAddress: 'Chicago, IL, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-25T22:00:00',
        },
        {
          PointZip: '32034',
          distanceMiles: 475,
          PointCity: 'Fernandina Beach',
          PointType: 'delivery',
          ShipperId: 47,
          PointOrder: 1,
          PointState: 'FL',
          ShipperName: 'LONG ITEM',
          PointAddress: '94016 Woodbrier Cir, Fernandina Beach, FL 32034, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-26T22:00:00',
        },
        {
          PointZip: '',
          distanceMiles: 370,
          PointCity: 'Washington',
          PointType: 'delivery',
          ShipperId: 55,
          PointOrder: 2,
          PointState: 'DC',
          ShipperName: 'STREETSHIPPER',
          PointAddress: '14th St NW, Washington, DC, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-27T22:00:00',
        },
      ],
      companyId: 261,
      p_status: 'R',
      pay_value: '13200',
      pay_time: '01/10/2020 - 01/17/2020',
      driverUserId: 169,
      ssn: '454545454',
      password: null,
      firstName: 'Dzejms',
      lastName: 'Cameroon',
      bankId: null,
      accountNumber: null,
      routingNumber: null,
      isOwner: 0,
      isOwnerAsCompany: 0,
      deviceId: null,
      status: 1,
      used: 1,
      protected: 0,
      createdAt: '2020-12-07T13:40:57',
      updatedAt: '2021-01-19T11:05:16',
      doc: {
        mvrData: [],
        testData: [],
        workData: [
          {
            id: 'f771838a-e1b1-4535-b8ac-591b19b110e1',
            endDate: null,
            startDate: '2020-12-07T13:40:56.255Z',
            endDateShort: null,
            startDateShort: '12/7/20',
          },
        ],
        licenseData: [],
        medicalData: [],
        additionalData: {
          note: null,
          type: 'single',
          email: 'dzems@ddd.com',
          phone: '5455556565',
          address: {
            city: 'Los Gatos',
            state: 'California',
            address: 'Los Gatos, CA, USA',
            country: 'US',
            zipCode: '',
            addressUnit: null,
            stateShortName: 'CA',
          },
          bankData: {
            id: null,
            bankLogo: null,
            bankName: null,
            bankLogoWide: null,
            accountNumber: null,
            routingNumber: null,
          },
          businessData: { taxId: null, isOwner: 0, businessName: null, isBusinessOwner: 0 },
          notifications: [],
        },
      },
    },
    {
      id: 189,
      pickupLocation: {
        city: 'New York',
        state: 'New York',
        address: 'New York, NY, USA',
        country: 'US',
        zipCode: '',
        stateShortName: 'NY',
      },
      deliveryLocation: {
        city: 'Washington',
        state: 'District of Columbia',
        address: '14th St NW, Washington, DC, USA',
        country: 'US',
        zipCode: '',
        streetName: '14th Street Northwest',
        streetNumber: '',
        stateShortName: 'DC',
      },
      route: [
        {
          PointZip: '',
          distanceMiles: 0,
          PointCity: 'New York',
          PointType: 'start',
          ShipperId: 26,
          PointOrder: 1,
          PointState: 'NY',
          ShipperName: 'SHIPER123',
          PointAddress: 'New York, NY, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-22T22:00:00',
        },
        {
          PointZip: '',
          distanceMiles: 45,
          PointCity: 'Chicago',
          PointType: 'pickup',
          ShipperId: 27,
          PointOrder: 2,
          PointState: 'IL',
          ShipperName: 'SHIPP456',
          PointAddress: 'Chicago, IL, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-25T22:00:00',
        },
        {
          PointZip: '32034',
          distanceMiles: 475,
          PointCity: 'Fernandina Beach',
          PointType: 'delivery',
          ShipperId: 47,
          PointOrder: 1,
          PointState: 'FL',
          ShipperName: 'LONG ITEM',
          PointAddress: '94016 Woodbrier Cir, Fernandina Beach, FL 32034, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-26T22:00:00',
        },
        {
          PointZip: '',
          distanceMiles: 370,
          PointCity: 'Washington',
          PointType: 'delivery',
          ShipperId: 55,
          PointOrder: 2,
          PointState: 'DC',
          ShipperName: 'STREETSHIPPER',
          PointAddress: '14th St NW, Washington, DC, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-27T22:00:00',
        },
      ],
      companyId: 261,
      p_status: 'R',
      pay_value: '13200',
      pay_time: '01/10/2020 - 01/17/2020',
      driverUserId: 173,
      ssn: '343434334',
      password: null,
      firstName: 'Dreive',
      lastName: 'Drdfs',
      bankId: null,
      accountNumber: null,
      routingNumber: null,
      isOwner: 0,
      isOwnerAsCompany: 0,
      deviceId: null,
      status: 1,
      used: 1,
      protected: 0,
      createdAt: '2020-12-09T16:14:19',
      updatedAt: '2021-01-19T11:05:23',
      doc: {
        mvrData: [],
        testData: [],
        workData: [
          {
            id: 'd15c14f4-4a4f-4628-947a-0d405dc6eab4',
            endDate: null,
            startDate: '2020-12-09T16:14:18.933Z',
            endDateShort: null,
            startDateShort: '12/9/20',
          },
        ],
        licenseData: [],
        medicalData: [],
        additionalData: {
          note: null,
          type: 'single',
          email: 'fds@dsfa.com',
          phone: '5555555555',
          address: {
            city: 'New Orleans',
            state: 'Louisiana',
            address: 'New Orleans, LA, USA',
            country: 'US',
            zipCode: '',
            addressUnit: null,
            stateShortName: 'LA',
          },
          bankData: {
            id: null,
            bankLogo: null,
            bankName: null,
            bankLogoWide: null,
            accountNumber: null,
            routingNumber: null,
          },
          businessData: { taxId: null, isOwner: 0, businessName: null, isBusinessOwner: 0 },
          notifications: [],
        },
      },
    },
    {
      id: 191,
      pickupLocation: {
        city: 'New York',
        state: 'New York',
        address: 'New York, NY, USA',
        country: 'US',
        zipCode: '',
        stateShortName: 'NY',
      },
      deliveryLocation: {
        city: 'Washington',
        state: 'District of Columbia',
        address: '14th St NW, Washington, DC, USA',
        country: 'US',
        zipCode: '',
        streetName: '14th Street Northwest',
        streetNumber: '',
        stateShortName: 'DC',
      },
      route: [
        {
          PointZip: '',
          distanceMiles: 0,
          PointCity: 'New York',
          PointType: 'start',
          ShipperId: 26,
          PointOrder: 1,
          PointState: 'NY',
          ShipperName: 'SHIPER123',
          PointAddress: 'New York, NY, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-22T22:00:00',
        },
        {
          PointZip: '',
          distanceMiles: 45,
          PointCity: 'Chicago',
          PointType: 'pickup',
          ShipperId: 27,
          PointOrder: 2,
          PointState: 'IL',
          ShipperName: 'SHIPP456',
          PointAddress: 'Chicago, IL, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-25T22:00:00',
        },
        {
          PointZip: '32034',
          distanceMiles: 475,
          PointCity: 'Fernandina Beach',
          PointType: 'delivery',
          ShipperId: 47,
          PointOrder: 1,
          PointState: 'FL',
          ShipperName: 'LONG ITEM',
          PointAddress: '94016 Woodbrier Cir, Fernandina Beach, FL 32034, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-26T22:00:00',
        },
        {
          PointZip: '',
          distanceMiles: 370,
          PointCity: 'Washington',
          PointType: 'delivery',
          ShipperId: 55,
          PointOrder: 2,
          PointState: 'DC',
          ShipperName: 'STREETSHIPPER',
          PointAddress: '14th St NW, Washington, DC, USA',
          PointCountry: 'US',
          PointDateTime: '2021-01-27T22:00:00',
        },
      ],
      companyId: 261,
      p_status: 'R',
      pay_value: '13200',
      pay_time: '01/10/2020 - 01/17/2020',
      driverUserId: 174,
      ssn: '454544432',
      password: null,
      firstName: 'Dvrs',
      lastName: 'Dsfa',
      bankId: null,
      accountNumber: null,
      routingNumber: null,
      isOwner: 0,
      isOwnerAsCompany: 0,
      deviceId: null,
      status: 1,
      used: 0,
      protected: 0,
      createdAt: '2020-12-10T12:40:43',
      updatedAt: '2021-01-17T17:15:45',
      doc: {
        mvrData: [],
        testData: [],
        workData: [
          {
            id: '873d418c-23f8-4f20-ad12-a85d160d1bc4',
            endDate: null,
            startDate: '2020-12-10T12:40:42.64Z',
            endDateShort: null,
            startDateShort: '12/10/20',
          },
        ],
        licenseData: [],
        medicalData: [],
        additionalData: {
          note: null,
          type: 'single',
          email: 'dsa@fa.com',
          phone: '5553433222',
          address: {
            city: 'Newark',
            state: 'New Jersey',
            address: 'Newark, NJ, USA',
            country: 'US',
            zipCode: '',
            addressUnit: null,
            stateShortName: 'NJ',
          },
          bankData: {
            id: null,
            bankLogo: null,
            bankName: null,
            bankLogoWide: null,
            accountNumber: null,
            routingNumber: null,
          },
          businessData: { taxId: null, isOwner: 0, businessName: null, isBusinessOwner: 0 },
          notifications: [],
        },
      },
    },
  ];

  showMoreItems() {
    this.showListCount = this.showListCount + 1;
    this.accountListTemp = this.accountList.slice(0, this.showListCount * this.showListNumber);
    if (this.chipSearch) { this.searchInsideList(this.chipSearch); }
  }

  showAllItems() {
    this.showListCount = this.accountList.length * this.showListNumber;
    this.accountListTemp = this.accountList;
  }

  selectFromLists(mod: any, ind: number) {
    if (this.selectedUserIndex == mod.id) {
      this.selectedUserIndex = 0;
      this.selectFromList.emit(null);
      return;
    }
    this.selectFromList.emit(mod);
    this.selectedUserIndex = mod.id;
  }

  ngOnInit(): void {
    this.accountListTemp = this.accountList.slice(0, this.showListCount * this.showListNumber);
    this.searchDateService.dataSource.pipe(takeUntil(this.destroy$)).subscribe((event: SearchFilterEvent) => {
      if (event && event.check) {
        this.chipSearch = event.searchFilter && event.searchFilter.chipsFilter ? event.searchFilter.chipsFilter : null;
        this.searchInsideList(
          event.searchFilter && event.searchFilter.chipsFilter ? event.searchFilter.chipsFilter : null
        );
      }
    });
  }

  searchInsideList(chip: ChipsFilter) {
    /* console.log(chip); */
    if (!chip) { return; }
    this.accountListTemp = this.accountList
      .filter((item) => {
        const full_name = item.firstName + ' ' + item.lastName;
        return full_name.toLowerCase().includes(chip.label.toLowerCase());
      })
      .slice(0, this.showListCount * this.showListNumber);
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }
}
